env:
  global:
    - secure: "Trfj9VBfVjSJe9LC3ZA4weUlatGIP44e2VOG8SOcqQL6p6JTpnxnGjM4VLIRqhzD9joBhi7baoOmncterNfmvIWI7fq+GVHM7JyMx/LcmS0h4lUUlIN49Tuz7iN+LMkfuoqUvtiD6wIIpEtQwh7t2LOOKv1QNdhaGhpZcSVh3J3rqb1prK+AjtOiYBuYT4sxicqyN1NgJ0dqGvP+xcDztTLy79u9UAtstXlU+yhUKSa+I4cYaoxc4eIFO6WFwCOrP8PEQnw2mCu42rHjMCLJsRRZIDK/FNwkqjgB3cIxQ+zPU2oiN7VzHBpmcTyiHQUHA3Yp6BOXlPLHNDHqxztRucawoClkYRIBmODzrIbqcxICZIVaT2qutVfceK9y5yTRUWrYYfpPwTaxivdMHaWsrvEfMy1EvoXO875+jHfUN9tI3u/U7FIDO7T+7/mTYDeVeyb5DLeYp+HZS4LQwd4RyZs6OcF/9sTwgKbEp8uixh1MY0GGEZNghBsOCTFcrVcnyfK07Gn5IMN5REQgKtX/QT8vJtMvpJneY1m1lMZ0Ek96iqq3abkhB0Z0X9adcBJtLJgEkvogujAhQKBAHCdolVihBlY4Lq2052w48huQ+kVzhqeRGqfzDLlNulP1bvF/iunKF7HsU1iuuEEB/aIGmQfrfVdrQJoyyteTLU7fTUA="
    - HUGO_RELEASE=0.14

install: ./scripts/get_deps.sh

script: ./scripts/build_all.sh

deploy:
    skip_cleanup: true
    provider: script
    script: ./scripts/deploy.sh
